apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretname }}
type: Opaque
data:
  # generate 16 chars long random string, base64 encode it and then double-quote the result string.
  username: {{ (printf "%s:%s" .Values.username (randAlphaNum 16)) | b64enc | quote }}